### ISSUE TITLE
a keyboard connected through a full-speed hub failed to work, screen shots

### ISSUE THREAD

**Issue by senggao** [VendelinSlezak/BleskOS#94]
**Environment**
real haradware, Dell laptop, 2 Ehcis, with RMHs

**Describe the bug**
1. I plugged in an external full-speed hub, through which I connected a low-speed usb 1.1 keyboard and a full-speed usb 2.0 keyboard. The keyboards failed to work.
2. I plugged in a high-speed hub, through which I connected the  low-speed usb 1.1 keyboard, the keyboard worked well. However the full-speed usb 2.0 keyboard failed to work after several times of plug in and out
3. In function usb_hid_device_set_protocol, shall 0x0A be a 0x0B

**Comment by VendelinSlezak** [comment]
Thank you for testing BleskOS and reporting bug.

Would it be possible for you to open and post content of System log (Main window>[F1] System board>[L] System log>[F2] Backup the log/send images of screen)? There should be messages what BleskOS detects and what exactly is hardware responding.

If you are unable to use any keyboard, you can open system log directly from bootloader, when you configure [a] Boot options to have debug messages On, and manual selecting of graphic mode Off. Then go back with [esc] and run option “BleskOS special boot options” Every part of logs during boot should be then showed on screen for 4 seconds.

**Comment by senggao** [comment]
![Image](https://github.com/user-attachments/assets/8c12bbab-2659-4c71-80be-c4a4f6df46dc)

![Image](https://github.com/user-attachments/assets/88d9cc6e-d766-4b86-bd34-562ff2193ded)

![Image](https://github.com/user-attachments/assets/1c4a48f5-8618-404f-9f66-0a5189eff428)

![Image](https://github.com/user-attachments/assets/7b5de1b3-56ae-4b68-8bff-8ff03d1afbf7)

![Image](https://github.com/user-attachments/assets/4f00dae0-9e1f-45a6-bf50-2ee3fbd5000c)

![Image](https://github.com/user-attachments/assets/8f833dfe-a246-48ef-8543-0b8b0d8ec7e6)

![Image](https://github.com/user-attachments/assets/595904ba-ba63-4115-912c-d9d70fedc388)

**Comment by VendelinSlezak** [comment]
Thank you for log. It seems that issue can be, as you pointed out, mistake in usb_hid_device_set_protocol. Here is image where this should be fixed. Would you please try it?

[bleskos_v2025u2_hid_protocol_fixed.img.zip](https://github.com/user-attachments/files/18524976/bleskos_v2025u2_hid_protocol_fixed.img.zip)

**Comment by senggao** [comment]
hello, 
I unpacked the _bleskos_v2025u2_hid_protocol_fixed.img.zip_, fetched _bleskos_v2025u2_hid_protocol_fixed.img_, which I burned by _dd_ command in Ubuntu into USB flash. The same problem still exists. That is, although the externel full-speed hub had been recognized, the keyboard had not been  recognized.

**Comment by VendelinSlezak** [comment]
Thank you for providing logs. It seems there is some issue with hub driver. I am currently rewriting all USB drivers to new and better version, so update will took some time, but when it will be done, hopefully it will remove also this issue.

**Comment by VendelinSlezak** [comment]
Hello, would you please try update 10 to see if it fixed this problem?

**Comment by senggao** [comment]
hello, sorry I haven't logged in Email for a long time. Alright, I would like to try.


         原始邮件
         
       
发件人：Vendelín Slezák ***@***.***&gt;
发件时间：2025年3月29日 21:55
收件人：VendelinSlezak/BleskOS ***@***.***&gt;
抄送：senggao ***@***.***&gt;, State change ***@***.***&gt;
主题：Re: [VendelinSlezak/BleskOS] a keyboard connected through afull-speed hub failed to work, screen shots (Issue #94)



VendelinSlezak left a comment (VendelinSlezak/BleskOS#94)

Hello, would you please try update 10 to see if it fixed this problem?
